name: vitessce-human-neocortex-env
channels:
- bioconda
- conda-forge
dependencies:
- python>=3.8
- anndata
- pandas
- numpy
- jupyterlab
- boto3
- zarr
- numcodecs
- scipy
- pip
- pip:
  - scanpy
  - vitessce==0.1.0a8